### ISSUE TITLE
Unpythonic usage of isinstance and is makes unit testing difficult

### ISSUE THREAD

**Issue by lietu** [vaidik/sherlock#12]
It seems sherlock is using isinstance in a fairly unpythonic way to check if the clients given to sherlock.configure() are "valid".

I was just trying out mocking pylibmc with [mockcache](https://pypi.python.org/pypi/mockcache/1.0.1), only to be greeted by this error:
```
ValueError: The provided object is not a valid clientobject. Client objects can only be instances 
of redis library's client class,python-etcd library's client class or pylibmc library's client class.
```

There is a workaround, registering a new backend.

Also it seems the MCLock class is using a somewhat unpythonic `self.client.add(*tuple(_args)) is True` in _acquire so this part of the code isn't compatible with mockcache either, as that seems to `return 1` instead.

This means you'll have to create a new Lock class as well:
```
import mockcache
import uuid
import sherlock

class MCMLock(sherlock.MCLock):
    def _acquire(self):
        owner = uuid.uuid4()

        _args = [self._key_name, str(owner)]
        if self.expire is not None:
            _args.append(self.expire)
        # Set key only if it does not exist
        if self.client.add(*tuple(_args)):
            self._owner = owner
            return True
        else:
            return False

sherlock.backends.register(
    name='MEMCACHED_MOCK',
    library='mockcache',
    client_class=Client,
    lock_class=MCMLock,
    default_args=([],),
    default_kwargs={'binary': True}
)
```

It would be nice if all this wasn't necessary though.

**Comment by vaidik** [comment]
Achieving compatibility with tones of libraries out there would be rather difficult for me to put together. There are many memcached and redis libraries already out there and at least more than 1 for etcd. I just decided to choose the ones that I thought are the most used, and I was using them as well for my projects and implemented backend classes accordingly. Moreover, I have heard about mockcache for the first time.

Coming to your points of unpythonic usage, I am not sure if that is entirely true because I am not absolutely clear on all the "pythonic" ways of doing things. I would love to discuss if you have more to educate me on that but I would put forth my rationale for going behind this design.

`sherlock.configure()` accepts only a set of backends that are available in sherlock by default. Since these backend implementations in `sherlock` use certain libraries and it is difficult to comply with a lot of libraries, the choice of clients gets limited to choice of backend implementations that come with sherlock as well as any extra implementation that you build yourself.

Now you ask, why does `sherlock.configure()` allow you to provide a custom client object? Here are the reasons:
* you may want to instantiate the supported clients with a different set of arguments that are not the defaults. So you can do something like `pylibmc.Client(*your_args, **your_kwargs)` and make pylibmc.MCLock use this client object.
* you can sub-class `pylibmc.Client` and override the client object to provide some custom implementation.

Checking the way I check valid client object in `sherlock` seemed like a sensible way of achieving this. Do you have a better work around? If yes, I would love to hear your thoughts.

The second point that you have made is something that I have explained earlier. There are just too many clients and complying to all of them is a difficult task. That is something I am not going to do anyways.
