### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by ashep** [vaidik/sherlock#17]
```
File "/env/lib/python3.5/site-packages/sherlock/lock.py", line 207
    except LockException, err:
                        ^
SyntaxError: invalid syntax
```

**Comment by rmariano** [comment]
I submitted #18 to address this particular issue

**Comment by vaidik** [comment]
Hey @rmariano and @ashep 

sherlock is now supported with Python 3 as well.

Sorry I was away for a very long time due to my commitments at work and didn't get a chance to look at your issues. I am committing to maintaining sherlock now.

Would appreciate to get more feedback and see more issues coming in :)

Also, thanks @rmariano for your PR :)
